### ISSUE TITLE
Does CoreUI-Vue require nodeJS constantly or only for the setup/installation phase?

### ISSUE THREAD

**Issue by FranckSCTV** [mrholek/CoreUI-Vue#1]
Hi,
I would like to use CoreUI-Vue for one website but the server doesn't support nodeJS.
Can I install nodeJS on my local machine, develop the admin interface there and then export the whole thing as static files so that I can use it on the server without any need of nodeJS?
Thanks a lot!

**Comment by xidedix** [comment]
In short: node.js is required for development only (npm, webpack etc.)
