### ISSUE TITLE
Minimizer bug

### ISSUE THREAD

**Issue by FantasticFiasco** [mrholek/CoreUI-Vue#20]
1. Minimize the sidebar
2. Increase the height of the browser window -> the minimizer button will follow the edge of the window
3. Decrease the height of the window -> The minimizer button will __not__ follow the edge of the window, and will no longer be visible in the browser.

![image](https://user-images.githubusercontent.com/8513095/31412152-508958ea-ae14-11e7-902a-e4dfdd144573.png)

**Comment by mrholek** [comment]
Can you check latest version?

**Comment by FantasticFiasco** [comment]
Still having the same issue, verified on git commit `f244f0258577eba9d509ec7e23186a9927ee264f`

**Comment by FantasticFiasco** [comment]
Seems to work now.
