### ISSUE TITLE
Can't upgrade Vue to 2.5.2

### ISSUE THREAD

**Issue by kailniris** [mrholek/CoreUI-Vue#21]
[Vue warn]: Invalid value for option "components": expected an Object, but got Array.

**Comment by kailniris** [comment]
https://github.com/bootstrap-vue/bootstrap-vue/issues/1201

**Comment by tmorehouse** [comment]
This will be fixed in the soon to be released v1.0.0 of Bootstrap-Vue.

**Comment by xidedix** [comment]
Bootstrap-Vue v1.x fixed this issue
closes #21
