### ISSUE TITLE
Why are we bundling bootstrap?

### ISSUE THREAD

**Issue by hailwood** [mrholek/CoreUI-Vue#22]
I've noticed we're bundling all the scss files for bootstrap.
I understand from #12 that we can't use the CDN because we're compiling the template with custom variables - but why aren't we pulling bootstrap in via npm?

This would ensure a more consistent experience, as it currently stands a user could submit a PR editing the core bootstrap files and suddenly CoreUI is no longer "bootstrap compatible".

Summary: Please consider loading bootstrap via npm rather than bundling it with the template.

**Comment by vpratfr** [comment]
I asked myself the same question today. +1 for pulling BS via NPM and importing it into coreUI via the appropriate node_module subfolder.

**Comment by farnetani** [comment]
Taking advantage of the question from the colleague above, I would really like to know if I could for example import the traditional bootstrap rather than using boostrap-vue, although I have seen that boostrap-vue is pretty cool. Could I have the 2 running at the same time?

**Comment by hailwood** [comment]
@farnetani there's no reason you actually need to use the bootstrap-vue components.
You can write the markup using standard bootstrap markup if you wish.

**Comment by hailwood** [comment]
Fixed in v1.0.4
