### ISSUE TITLE
Bootstrap-Vue 1.0.0 just released

### ISSUE THREAD

**Issue by tmorehouse** [mrholek/CoreUI-Vue#28]
https://www.npmjs.com/package/bootstrap-vue

This version replaced v10.0-beta.9

**Comment by xidedix** [comment]
v1.0.6

**Comment by jordanboston** [comment]
Is this template 100% compatible with bootstrap-vue?  I have an existing project and it is already built upon that.

Also, I am not seeing any info about using this admin template within an existing Vue project.  It only shows it as a standalone.  Any thoughts on that, or will I just need to manually try to bring things over into my project?
