### ISSUE TITLE
[Vue warn]: Invalid value for option "components": expected an Object, but got Array. @ vue.esm.js?efeb:571 

### ISSUE THREAD

**Issue by jericopulvera** [mrholek/CoreUI-Vue#33]
[Vue warn]: Invalid value for option "components": expected an Object, but got Array.
warn @ vue.esm.js?efeb:571
assertObjectType @ vue.esm.js?efeb:1398
mergeAssets @ vue.esm.js?efeb:1223
mergeField @ vue.esm.js?efeb:1447
mergeOptions @ vue.esm.js?efeb:1438
Vue.extend @ vue.esm.js?efeb:4672
Vue.(anonymous function) @ vue.esm.js?efeb:4755
install @ bootstrap-vue.esm.js?b024:13470
Vue.use @ vue.esm.js?efeb:4614
(anonymous) @ main.js?1c90:8
(anonymous) @ app.js:1073
__webpack_require__ @ app.js:679
fn @ app.js:89
(anonymous) @ app.js:963
__webpack_require__ @ app.js:679
(anonymous) @ app.js:725
(anonymous) @ app.js:728

How do I remove this annoying warning

**Comment by tmorehouse** [comment]
This was an issue with a previous version of bootstrap-vue.  The latest version (v1.0.x non-beta branch) has this corrected.

**Comment by tmorehouse** [comment]
Although CoreUI is still referencing bootstrap-vue v1.0.0-beta.9.  It should be updated to v1.0.2 (although v1.0.3 is just around the corner)

**Comment by xidedix** [comment]
Hi @tmorehouse - thank you for the help and support! 
We have postponed some updates for the next release (which is just around the corner).

**Comment by vvelkovski** [comment]
I see the same error in v1.0.4
