### ISSUE TITLE
Rename Header, Footer and Aside components

### ISSUE THREAD

**Issue by donalmurtagh** [mrholek/CoreUI-Vue#46]
Vue components should not have the same names as HTML elements, so `Header` and `Footer` and `Aside` should be renamed. When the app is built, these component names cause errors such as:

> ERROR LOG: '[Vue warn]: Do not use built-in or reserved HTML elements as component id: header'

**Comment by xidedix** [comment]
hi @donalmurtagh for the heads up!
We are aware of this issue already. A fix is around the corner.

**Comment by donalmurtagh** [comment]
@xidedix is there already an open issue for this?

**Comment by xidedix** [comment]
well, #46 actually :)
