### ISSUE TITLE
Unable to start with this project.

### ISSUE THREAD

**Issue by jaideepghosh** [mrholek/CoreUI-Vue#49]
Trying to install and run this, and following these steps mentioned in this page: http://coreui.io/docs/getting-started/vue-js-version/

But wen I'm running `npm run dev` It is returning following error:

```
module.js:538
    throw err;
    ^

Error: Cannot find module 'shelljs'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/cc-server/TaxiWala/public/admin/CoreUI-Vue/Vue_Starter/build/check-versions.js:4:13)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @coreui/vue@1.0.8 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @coreui/vue@1.0.8 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-17T17_02_13_943Z-debug.log
```

(I'm New in Node and Vuejs)

**Comment by xidedix** [comment]
Hi @jaideepghosh 
I assume that you've got node & npm installed properly.

please try this way: 
````bash
cd Vue_Starter  
npm i 
npm start
````

**Comment by jaideepghosh** [comment]
Hi @xidedix 
Thank you for your response.I tried this method, but still it is not working for me. When I'm executing `npm i` Then I got following error :

**Comment by xidedix** [comment]
Cannot reproduce.

You've got `no such file or directory` error in `node_modules/node-sass/vendor` see also #53 

Sometimes things go wrong with `npm install` 
please try:
- remove `node_modules` directory 
- remove `package-lock.json` file
- then `npm install`

**Comment by stranger26** [comment]
@jaideepghosh If you're Windows user and using git bash, switching to powershell apparently resolves this issue.
