### ISSUE TITLE
Unable to start with this project!!!

### ISSUE THREAD

**Issue by rolitter** [mrholek/CoreUI-Vue#53]
### CoreUI-Vue
1.0.10

### OS/Browsers version
mac OS /chrome63.0.3239.132

### node version/npm version
 "node": " 8.9.4",
 "npm": "5.6.0"

### Steps to reproduce
cd Vue_Full_Project
npm i 
npm run start

### What is actually happening?
![image](https://user-images.githubusercontent.com/27326998/35847690-3fedaed8-0b56-11e8-910f-6d8e58e7c306.png)

![image](https://user-images.githubusercontent.com/27326998/35847492-93f63618-0b55-11e8-8c4e-88d80e2a635b.png)

![image](https://user-images.githubusercontent.com/27326998/35847720-62f69a3e-0b56-11e8-9ae6-b097efbcd6f8.png)

**Comment by xidedix** [comment]
Cannot reproduce.

You've got `no such file or directory` error in `node_modules/node-sass/vendor`

Sometimes things go wrong with `npm install` 
please try:
- remove `node_modules` directory 
- remove `package-lock.json` file, 
- then `npm install`

**Comment by rolitter** [comment]
@xidedix 😘Thanks,this problem has been solved, Because GWF caused this problem.
