### ISSUE TITLE
cannot get / error

### ISSUE THREAD

**Issue by mohsenpayro** [mrholek/CoreUI-Vue#56]
hi,
i just downloaded the project and after installing dependencies, ran npm run dev and i only get this text in the browser: Cannot get /

**Comment by xidedix** [comment]
hi @mohsenpayro 
Please provide steps to reproduce and other information that might be useful, such as
versions of web browser, os, node, npm.

**Comment by mohsenpayro** [comment]
oh, it's working now. the problem was node-sass. my internet service provider has blocked access to some websites and i had to use vpn to install the dependencies.
thanks for answering.

**Comment by xidedix** [comment]
I’m glad you got that sorted out!
