### ISSUE TITLE
getting "Unexpected token: punc" error when building for production

### ISSUE THREAD

**Issue by Davidriquelme** [mrholek/CoreUI-Vue#57]
getting this error when building for production:

ERROR in static/js/vendor.de54eb355154926716b6.js from UglifyJs
Unexpected token: punc ()) [./node_modules/mini-toastr/mini-toastr.js:12,0][static/js/vendor.de54eb355154926716b6.js:99039,14]

Does anyone knows the workaround ?

**Comment by xidedix** [comment]
hi @Davidriquelme 
Turns out that `mini-toastr v0.7.2` uses es6 and UglifyJS fails...

As temp workaround please use `v0.6.6` of `mini-toastr` - modify `dependencies` of your `package.json` 
from:
````js
"mini-toastr": "0.7.2",
````
to:
````js
"mini-toastr": "0.6.6",
````

**Comment by Davidriquelme** [comment]
perfect, thanks!! (it worked)
