### ISSUE TITLE
Vue_Full_Project not working with CoreUI Pro

### ISSUE THREAD

**Issue by kieraneglin** [mrholek/CoreUI-Vue#58]
After buying CoreUI pro, the `Vue_Full_Project` example doesn't work as expected.  Several errors are thrown during compilation and the page that launches is blank.

`Vue_Starter` works as expected.

**Comment by xidedix** [comment]
Hi @kieraneglin
Please provide error logs, steps to reproduce and other information that might be useful to investigate this issue, such as versions of web browser, os, node, npm.

**Comment by kieraneglin** [comment]
@xidedix my apologies for the poor error report, yesterday was very busy.

Either way, the issue is that Lodash isn't a dependency in the `Vue_Full_Project` package.json.  After a `yarn add lodash`, everything cleared up!

I know it's not important at this point, but here are my versions anyway.

**Versions**
**OS**: OS X 10.11
**Node**: Tested on 8.9.4 and 9.5.0
**NPM**: 5.6.0
**Yarn**: 0.16.1 (I use Yarn over NPM)
**Browser**: Doesn't matter

**Comment by xidedix** [comment]
sometimes things go wrong with `npm install`
glad you got that sorted out @kieraneglin
