### ISSUE TITLE
(Vue JS Starter / Laravel Mix)  Dashboard content displays smaller than advertised.

### ISSUE THREAD

**Issue by humblecoder** [mrholek/CoreUI-Vue#6]
Just "compiled" the latest "vue js starter" using Mix (Laravel 5.5dev).  After fixing a couple of SCSS and path-related bugs, I got the dashboard up and running smoothly.  The only issue I'm currently having is that the site appears to be defaulting to the mobile version despite viewing on the desktop (Safari/Chrome/Opera/FF).  All images, icons, and wording are tiny.  Any ideas?

**Comment by humblecoder** [comment]
My mistake.  I thought I'd removed all base Laravel formatting.  Dashboard displays correctly.

**Comment by vpratfr** [comment]
Hi,

Any chance you could share some tips & hints about integration into mix? I am starting a new project today.
