### ISSUE TITLE
What is reason behind using JSON.parse to evaluate NODE_ENV?

### ISSUE THREAD

**Issue by jantajov** [mrholek/CoreUI-Vue#60]
I  came across the following line of code: 

https://github.com/mrholek/CoreUI-Vue/blob/4be9d2dce2073b17e2c8afbfb6bca2aa45f25628/Vue_Full_Project/build/dev-server.js#L5

What is reason for parsing the NODE_ENV using JSON.parse?

**Comment by xidedix** [comment]
It's rather webpack config question.
Please take a look at [DefinePlugin](https://webpack.js.org/plugins/define-plugin/)
and vuejs-templates [Environment Variables](https://github.com/vuejs-templates/webpack/blob/develop/docs/env.md) 
Hope this helps

**Comment by jantajov** [comment]
Helps a lot! 
/close
